language: python
sudo: false
os:
  - linux

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch

before_install:
  - pip install codecov

install: "pip install -r dev-requirements.txt"

# command to run tests
script:
  - "PYTHONPATH=. py.test tests/"

after_success:
  - codecov